name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
	  matrix:
		include:
		  - context: ./eureka-server/
		    file: ./eureka-server/Dockerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/smp:eureka-server
      - context: ./api-gateway/
		    file: ./api-gateway/Dockerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/smp:api-gateway

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      - name: Build and test Spring Boot apps
        run: |
          springApps=("eureka-server" "api-gateway" "administration-service" "user-service")

          for app in "${springApps[@]}"; do
            cd $app
            mvn clean test package
            cd ..
          done

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push images to docker hub
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: true
          tags: ${{ matrix.tags }}
